name: Ekam Examples CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  api_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Run API Tests
      run: ./gradlew runApiTests
    - name: Upload API Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: api_tests
        path: allure-report/ui

  web_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: setup chrome
        uses: browser-actions/setup-chrome@latest
      - name: Run Web Tests
        run: ./gradlew runWebTests -Dweb.headless=true
      - name: Upload API Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: web_test
          path: allure-report/ui

  mobile_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install and Run Appium Server
        uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4
      - name: setup android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            adb devices
            ./gradlew runMobileTests --stacktrace
      - name: Upload API Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: mobile_test
          path: build/reports/tests/runMobileTests